<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TempController;
use Illuminate\Support\Facades\Route;

//Route::get('temp', function() {
//    $categoryRepository = new \Webkul\Category\Repositories\CategoryRepository();
//
//    $rotors_custom_fields_titles = [
//        'Year',
//        'Brake System',
//        'Vehicle Type',
//        'Application',
//        'Bolt Hardware Included',
//        'Rotor Type',
//        'Rotor Weight (lb)',
//        'Rotor Weight (kg)',
//        'Overall Diameter (in)',
//        'Overall Diameter (mm)',
//        'Disc Thickness (in)',
//        'Disc Thickness (mm)',
//        'Minimum Thickness (in)',
//        'Minimum Thickness (mm)',
//        'Overall Depth (in)',
//        'Overall Depth (mm)',
//        'Pilot Diameter (in)',
//        'Pilot Diameter (imm)',
//        'Bolt Circle Diameter (in)',
//        'Bolt Circle Diameter (mm)',
//        'Bolt Hole Diameter',
//        'Bolt Hole Count',
//        'ABS',
//        'Availability Status',
//        'UPC Code',
//        'Carton Weight (lb)',
//        'Carton Length (in)',
//        'Carton Width (in)',
//        'Carton Height (in)',
//        'Items per Case',
//        'Minimum Order QTY',
//        'PCS/ Pallet',
//        'Country of Origin',
//        'HTS Code',
//        'VMRS Code',
//        'Warranty',
//    ];
//    $rotors_custom_fields_names = [
//        'year',
//        'brake_system',
//        'vehicle_type',
//        'application',
//        'bolt_hardware_included',
//        'rotor_type',
//        'rotor_weight_lb',
//        'rotor_weight_kg',
//        'overall_diameter_in',
//        'overall_diameter_mm',
//        'disk_thickness_in',
//        'disk_thickness_mm',
//        'minimum_thickness_in',
//        'minimum_thickness_mm',
//        'overall_depth_in',
//        'overall_depth_mm',
//        'pilot_diameter_in',
//        'pilot_diameter_mm',
//        'bolt_circle_diameter_in',
//        'bolt_circle_diameter_mm',
//        'bolt_hole_diameter',
//        'bolt_hole_count',
//        'abs',
//        'availability_status',
//        'upc_code',
//        'carton_weight_lb',
//        'carton_length_in',
//        'carton_width_in',
//        'carton_height_in',
//        'items_per_case',
//        'minimum_order_qty',
//        'pcs_per_pallet',
//        'country_of_origin',
//        'hts_code',
//        'vmrs_code',
//        'warranty',
//    ];
//    $rotors_custom_fields_types = [
//        'Text',
//        'Text',
//        'Selection',
//        'Text',
//        'Selection',
//        'Selection',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Text',
//        'Number',
//        'Selection',
//        'Selection',
//        'Text',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Number',
//        'Text',
//        'Text',
//        'Text',
//        'Selection',
//    ];
//    $rotors_custom_fields_is_required = [
//        'Yes',
//        'Yes',
//        'Yes',
//        'No',
//        'No',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//        'No',
//        'No',
//        'No',
//        'No',
//        'No',
//        'No',
//        'Yes',
//        'Yes',
//        'No',
//        'Yes',
//        'No',
//        'No',
//        'No',
//        'Yes',
//        'Yes',
//        'No',
//        'Yes',
//        'Yes',
//        'Yes',
//        'Yes',
//    ];
//    $rotors_custom_fields_selection_options = [
//        '',
//        '',
//        'Transit / Coach, Trailer, Truck / Trailer, Truck, Trailer',
//        '',
//        'Yes, No',
//        'Hat, U-Shaped, Flat',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        'No, Cast-In, Bolt-On',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '',
//        '12 Months / Unlimited',
//    ];
//    $rotors_category = [
//          "locale" => "all",
//          "name" => "test test test ROTORS",
//          "status" => "1",
//          "position" => "1",
//          "display_mode" => "products_and_description",
//          "description" => "<p>test test test ROTORS</p>",
//          "image" => [
//              'image_1' => ''
//          ],
//          "category_icon_path" => [
//              'image_1' => ''
//          ],
//          "attributes" => ['11'],
//          "meta_title" => "",
//          "slug" => "rotors",
//          "meta_description" => "",
//          "meta_keywords" => "",
//          "custom_fields_titles" => $rotors_custom_fields_titles,
//          "custom_fields_names" => $rotors_custom_fields_names,
//          "custom_fields_types" => $rotors_custom_fields_types,
//          "custom_fields_is_required" => $rotors_custom_fields_is_required,
//          "custom_fields_selection_options" => $rotors_custom_fields_selection_options,
//    ];
//
//    $created_category = $categoryRepository->create($rotors_category);
//
//    dd($created_category);
//});

Route::get('temp', [TempController::class, 'index'])->name('temp');